// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWTQ4HErewNwd9FFO9G0hmtkejJWE_ix4',
    appId: '1:701299435098:web:dae8456ca96aadcb801a63',
    messagingSenderId: '701299435098',
    projectId: 'mbongi-1d48e',
    authDomain: 'mbongi-1d48e.firebaseapp.com',
    storageBucket: 'mbongi-1d48e.appspot.com',
    measurementId: 'G-M7MN2RF5Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX14se7-LQ7uoHiaCQ4QAPDZ62a-na3PM',
    appId: '1:701299435098:android:1f393e62522d094c801a63',
    messagingSenderId: '701299435098',
    projectId: 'mbongi-1d48e',
    storageBucket: 'mbongi-1d48e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx7va4LYjvunrQab-tP32H5Ox8l3Zp90c',
    appId: '1:701299435098:ios:ee435c0693d27c3b801a63',
    messagingSenderId: '701299435098',
    projectId: 'mbongi-1d48e',
    storageBucket: 'mbongi-1d48e.appspot.com',
    iosClientId: '701299435098-dgbaai81p256gdib1jmrkrfr4c678812.apps.googleusercontent.com',
    iosBundleId: 'cg.rbns.mbongi',
  );
}
